--------------------PASAJERO--------------------
/*PERMITE INGRESAR LOS DATOS DEL PASAJERO*/
CREATE PROCEDURE sp_Pasajero
@NOMPASAJERO VARCHAR(100),
@APEPASAJERO VARCHAR(100),
@RAZSPASAJERO VARCHAR(100),
@RUCPASAJERO CHAR(12),
@TIPDOCUPASAJERO VARCHAR(100),
@NUMDOCU CHAR(10),
@ORIGENPASAJERO VARCHAR(100),
@EDADPASAJERO VARCHAR(100),
@DESTINOPASAJERO VARCHAR(100)
AS
BEGIN
INSERT INTO Pasajero
(nomPasajero,apePasajero,razsPasajero,rucPasajero,tipDocuPasajero,numDocu,origenPasajero,edadPasajero,destinoPasajero)
VALUES
(UPPER(@NOMPASAJERO),UPPER(@APEPASAJERO),UPPER(@RAZSPASAJERO),@RUCPASAJERO,UPPER(@TIPDOCUPASAJERO),@NUMDOCU,@ORIGENPASAJERO,
UPPER(@EDADPASAJERO),@DESTINOPASAJERO)
END
GO


------------------BOLETA-------------------------
/*PERMITE INGRESAR LOS DE LA BOLETA*/
CREATE PROCEDURE SP_BOLETA
@COSTO VARCHAR(100)

AS
BEGIN
INSERT INTO Boleta
(costo)
VALUES
(@COSTO)
END
GO

------------------------FECHA TRANSPORTE--------------------------
/*PERMITE INGRESAR LA FECHA DE TRANSPORTE*/
CREATE PROCEDURE SP_FECHATRANSPORTE
@FECHATRANS VARCHAR(100),
@HORAPRATIDA VARCHAR(100)

AS
BEGIN
INSERT INTO FechaTransporte
(fechaTrans,horaPratida)
VALUES
(@FECHATRANS,@HORAPRATIDA)
END
GO


--------------------SERVICIOS-------------------------
/*PERMITE REGISTRAR LOS DATO DE SERVICIO DE TRANSPORTE*/
CREATE PROCEDURE SP_SERVICIOS
@ASIENTOS VARCHAR(100),
@CANTIDAD VARCHAR(100)

AS
BEGIN
INSERT INTO Servicios
(asientos,cantidad)
VALUES
(@ASIENTOS,@CANTIDAD)
END
GO